import type { TabDefinition } from '../../types';
import { figmaAssets } from '../figmaAssets';

// 这里维护 玩玩 AI 页的拼贴配置。
export const aiTab: TabDefinition = {
  id: 'ai',
  label: '玩玩 AI',
  themeClass: 'theme-pink',
  boardTextureSrc: figmaAssets.boardTexture,
  items: [
    {
      id: 'hkb-ai-card',
      imageSrc: '/assets/tiezhi/4-1.png',
      kind: 'photo',
      x: 450,
      y: 160,
      width: 400,
      className: 'floating-cutout text-hidden',
    },
    {
      id: 'hkb-ai-card',
      imageSrc: '/assets/tiezhi/4-2.png',
      kind: 'photo',
      x: 920,
      y: 280,
      width: 300,
      zIndex:4,
      rotate: 6,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'hkbAI' },
      className: 'floating-cutout text-hidden',
    },
    {
      id: 'AIbank-card',
      imageSrc: '/assets/tiezhi/4-3.png',
      kind: 'photo',
      x: 620,
      y: 300,
      width: 320,
      zIndex:3,
      rotate: -4,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'AIBank' },
      className: 'floating-cutout text-hidden',
    },
    {
      id: 'maoxuan-card',
      imageSrc: '/assets/tiezhi/4-4.png',
      kind: 'photo',
      x: 320,
      y: 250,
      width: 340,
      zIndex:2,
      rotate: 5,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'maoxuan' },
      className: 'floating-cutout text-hidden',
    },
    {
      id: 'jinyong-card',
      imageSrc: '/assets/tiezhi/4-5.png',
      kind: 'photo',
      x: 30,
      y: 300,
      width: 320,
      rotate: -7,
      zIndex:1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'jinyong' },
      className: 'floating-cutout text-hidden',
    },
  ],
};
