import type { TabDefinition } from '../../types';

// 这里维护 AI漫游 页的拼贴配置。
export const aiTab: TabDefinition = {
  id: 'ai',
  label: 'AI漫游',
  themeClass: 'theme-pink',
  items: [
    {
      id: 'ai-business',
      title: '解决真实业务',
      x: 160,
      y: 120,
      width: 280,
      height: 80,
      className: 'plain-copy ai-module',
    },
    {
      id: 'duizhang',
      title: 'duizhang',
      x: 180,
      y: 230,
      width: 240,
      height: 140,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'duizhang' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'bank',
      title: 'bank',
      x: 180,
      y: 400,
      width: 240,
      height: 140,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'bank' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'ai-efficiency',
      title: '提效',
      x: 500,
      y: 120,
      width: 280,
      height: 80,
      className: 'plain-copy ai-module',
    },
    {
      id: 'codex',
      title: 'codex',
      x: 520,
      y: 215,
      width: 240,
      height: 120,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'codex' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'book',
      title: 'book',
      x: 520,
      y: 360,
      width: 240,
      height: 120,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'book' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'map',
      title: 'map',
      x: 520,
      y: 505,
      width: 240,
      height: 120,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'map' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'ai-interaction',
      title: '探索新交互',
      x: 840,
      y: 120,
      width: 280,
      height: 80,
      className: 'plain-copy ai-module',
    },
    {
      id: 'jinyong',
      title: 'jinyong',
      x: 860,
      y: 230,
      width: 240,
      height: 140,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'jinyong' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'write',
      title: 'write',
      x: 860,
      y: 400,
      width: 240,
      height: 140,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'write' },
      className: 'ai-image-placeholder',
    },
  ],
};
