import type { TabDefinition } from '../../types';

// 这里维护 AI漫游 页的拼贴配置。
export const aiTab: TabDefinition = {
  id: 'ai',
  label: 'AI 漫游',
  themeClass: 'theme-pink',
  items: [
    {
      id: 'hkbAI',
      title: 'hkbAI',
      imageSrc: '/assets/tiezhi/3-hkbAI.webp',
      x: 30,
      y: 160,
      width: 340,
      rotate:-3,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'hkbAI' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'bank',
      title: 'bank',
      imageSrc: '/assets/tiezhi/3-bank.webp',
      x: 40,
      y: 480,
      width: 340,
      rotate:2,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'bank' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'codex',
      title: 'codex',
      imageSrc: '/assets/tiezhi/3-codex.webp',
      x: 460,
      y: 195,
      width: 340,
      rotate:4,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'codex' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'book',
      title: 'book',
      imageSrc: '/assets/tiezhi/3-book.webp',
      x: 460,
      y: 340,
      width: 340,
      rotate:-2,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'book' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'map',
      title: 'map',
      imageSrc: '/assets/tiezhi/3-map.webp',
      x: 460,
      y: 565,
      width: 340,
      rotate:2,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'map' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'jinyong',
      title: 'jinyong',
      imageSrc: '/assets/tiezhi/3-jinyong.webp',
      x: 900,
      y: 190,
      width: 320,
      rotate:-2,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'jinyong' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'write',
      title: 'write',
      imageSrc: '/assets/tiezhi/3-write.webp',
      x: 880,
      y: 460,
      width: 320,
      rotate:5,
      hoverEffect: 'breathe',
      action: { type: 'openModal', id: 'write' },
      className: 'ai-image-placeholder',
    },
    {
      id: 'interest',
      title: 'interest',
      imageSrc: '/assets/tiezhi/interest.webp',
      x: 400,
      y: 80,
      width: 500,
      rotate:0,
      hoverEffect: 'breathe',
      className: 'ai-image-placeholder',
    },
  ],
};
