import type { TabDefinition } from '../../types';

// 这里维护 一些设计 页的拼贴配置。
export const designTab: TabDefinition = {
  id: 'design',
  label: '一些设计',
  themeClass: 'theme-olive',
  items: [
    // 回款宝介绍
    {
      id: 'huikuanbao-card',
      imageSrc: '/assets/tiezhi/2-hkb.webp',
      x: 180,
      y: 33,
      width: 420,
      height: 373,
      rotate:5,
      zIndex: 2,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'huikuanbao' },
      className: 'floating-cutout',
    },
    // 回款宝老板贴图
    {
      id: 'huikuanbao-boss',
      imageSrc: '/assets/tiezhi/2-boss.webp',
      x: 520,
      y: 10,
      width: 85,
      rotate:10,
      zIndex: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 回款宝财务
    {
      id: 'huikuanbao-caiwu',
      imageSrc: '/assets/tiezhi/2-caiwu.webp',
      x: 0,
      y: 40,
      width: 200,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 回款宝发票贴图
    {
      id: 'huikuanbao-bill',
      imageSrc: '/assets/tiezhi/2-bill.webp',
      x: 140,
      y: 280,
      width: 80,
      rotate:-20,
      zIndex: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 他行转入卡片
    {
      id: 'thzr-card',
      imageSrc: '/assets/tiezhi/2-zr.webp',
      x: 60,
      y: 440,
      width: 520,
      rotate:2,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'thzr' },
      className: 'floating-cutout',
    },
    // 他行转入配图
    {
      id: 'thzr-photo',
      imageSrc: '/assets/tiezhi/2-heiban.webp',
      x: 480,
      y: 460,
      width: 100,
      rotate:10,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 门店装修卡片
    {
      id: 'mdzx-card',
      imageSrc: '/assets/tiezhi/2-mdzx.webp',
      x: 700,
      y: 10,
      width: 400,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'mdzx' },
      className: 'floating-cutout',
    },
    // 宜家
    {
      id: 'yijia',
      imageSrc: '/assets/tiezhi/2-IKEA.webp',
      x: 1040,
      y: 100,
      width: 80,
      rotate:10,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 点评截图
    {
      id: 'dianping',
      imageSrc: '/assets/tiezhi/2-dianping.webp',
      x: 1060,
      y: 160,
      width: 80,
      rotate:5,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 农村金融调研
    {
      id: 'nc-card',
      imageSrc: '/assets/tiezhi/2-nc.webp',
      x: 680,
      y: 350,
      width: 440,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'nongcun' },
      className: 'floating-cutout',
    },
    //种柑橘
    {
      id: 'nc-ganju',
      imageSrc: '/assets/tiezhi/2-nongcun.webp',
      x: 1080,
      y: 550,
      width: 180,
      rotate:0,
      zIndex: 2,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 老头
    {
      id: 'nc-laotou',
      imageSrc: '/assets/tiezhi/2-laotou.webp',
      x: 1050,
      y: 480,
      width: 120,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 辣椒
    {
      id: 'nc-lajiao',
      imageSrc: '/assets/tiezhi/2-lajiao.webp',
      x: 700,
      y: 700,
      width: 120,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
  ],
};
