import type { TabDefinition } from '../../types';
import { figmaAssets } from '../figmaAssets';

// 这里维护 一些设计 页的拼贴配置。
export const designTab: TabDefinition = {
  id: 'design',
  label: '一些设计',
  themeClass: 'theme-olive',
  boardTextureSrc: figmaAssets.boardTexture,
  items: [
    // 回款宝介绍
    {
      id: 'huikuanbao-card',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-hkb.png',
      x: 210,
      y: 33,
      width: 380,
      height: 373,
      rotate:0,
      zIndex: 2,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'huikuanbao' },
      className: 'floating-cutout',
    },
    // 回款宝老板贴图
    {
      id: 'huikuanbao-boss',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-boss.png',
      x: 520,
      y: 10,
      width: 85,
      rotate:10,
      zIndex: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 回款宝财务
    {
      id: 'huikuanbao-caiwu',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-caiwu.png',
      x: 0,
      y: 40,
      width: 230,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 回款宝发票贴图
    {
      id: 'huikuanbao-bill',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-bill.png',
      x: 570,
      y: 320,
      width: 70,
      rotate:30,
      zIndex: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 回款宝手机贴图
    {
      id: 'huikuanbao-phone',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-phone.png',
      x: 140,
      y: 260,
      width: 100,
      rotate:-10,
      zIndex: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 他行转入卡片
    {
      id: 'thzr-card',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-zr.png',
      x: 20,
      y: 500,
      width: 600,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'thzr' },
      className: 'floating-cutout',
    },
    // 他行转入配图
    {
      id: 'thzr-photo',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-heiban.png',
      x: 420,
      y: 500,
      width: 140,
      rotate:10,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 门店装修卡片
    {
      id: 'mdzx-card',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-mdzx.png',
      x: 800,
      y: 10,
      width: 380,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'mdzx' },
      className: 'floating-cutout',
    },
    // 宜家
    {
      id: 'yijia',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-IKEA.png',
      x: 1080,
      y: 100,
      width: 100,
      rotate:10,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 点评截图
    {
      id: 'dianping',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-dianping.png',
      x: 1140,
      y: 160,
      width: 100,
      rotate:-6,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 农村金融调研
    {
      id: 'nc-card',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-nc.png',
      x: 750,
      y: 350,
      width: 400,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      action: { type: 'openProject', projectId: 'nongcun' },
      className: 'floating-cutout',
    },
    //种柑橘
    {
      id: 'nc-ganju',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-nongcun.png',
      x: 1080,
      y: 550,
      width: 180,
      rotate:0,
      zIndex: 2,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 老头
    {
      id: 'nc-laotou',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-laotou.png',
      x: 1050,
      y: 480,
      width: 120,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 辣椒
    {
      id: 'nc-lajiao',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-lajiao.png',
      x: 700,
      y: 700,
      width: 120,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 老太
    {
      id: 'nc-laotai',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-laotai.png',
      x: 670,
      y: 500,
      width: 120,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
    // 拿纸
    {
      id: 'nc-nazhi',
      kind: 'photo',
      imageSrc: '/public/assets/tiezhi/2-ncz.png',
      x: 800,
      y: 720,
      width: 80,
      rotate:0,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout',
    },
  ],
};
