import type { TabDefinition } from '../../types';
import { figmaAssets } from '../figmaAssets';

// 这里维护 看看世界 页的拼贴配置。
export const travelTab: TabDefinition = {
  id: 'travel',
  label: '看看世界',
  themeClass: 'theme-blue',
  boardTextureSrc: figmaAssets.boardTexture,
  items: [
    {
      id: '5-1',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-1.png',
      x: 34,
      y: 60,
      width: 204,
      rotate: -2,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-2',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-2.png',
      x: 280,
      y: 30,
      width: 180,
      rotate: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-3',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-3.png',
      x: 1000,
      y: 550,
      width: 160,
      rotate: -2,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-4',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-4.png',
      x: 820,
      y: 28,
      width: 204,
      zIndex: 1,
      rotate: 2,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-5',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-5.png',
      x: 1060,
      y: 60,
      width: 140,
      rotate: -2,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-8',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-8.png',
      x: 426,
      y: 298,
      width: 176,
      rotate: 1,
      zIndex: 2,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-9',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-9.png',
      x: 530,
      y: 44,
      width: 250,
      rotate: -1,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-11',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-11.png',
      x: 990,
      y: 360,
      width: 220,
      rotate: 3,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-12',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-12.png',
      x: 80,
      y: 310,
      width: 230,
      rotate: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-13',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-13.png',
      x: 124,
      y: 530,
      width: 250,
      rotate: -1,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-14',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-14.png',
      x: 450,
      y: 580,
      width: 200,
      rotate: 1,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-15',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-15.png',
      x: 660,
      y: 330,
      width: 240,
      rotate: -1,
      zIndex: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
    {
      id: '5-16',
      kind: 'photo',
      imageSrc: '/assets/tiezhi/5-16.png',
      x: 730,
      y: 600,
      width: 220,
      rotate: 1,
      hoverEffect: 'breathe',
      className: 'floating-cutout travel-photo',
    },
  ],
};
