import type { ProjectDefinition } from '../../types';

export const huikuanbaoProject: ProjectDefinition = {
  id: 'huikuanbao',
  title: '回款宝重构',
  detail: {
    type: 'image',
    images: [
      '/project-images/hkb/hkb-001.webp',
      '/project-images/hkb/hkb-002.webp',
      '/project-images/hkb/hkb-003.webp',
      '/project-images/hkb/hkb-004.webp',
      '/project-images/hkb/hkb-005.webp',
      '/project-images/hkb/hkb-006.webp',
      '/project-images/hkb/hkb-007.webp',
      '/project-images/hkb/hkb-008.webp',
      '/project-images/hkb/hkb-009.webp',
      '/project-images/hkb/hkb-010.webp',
      '/project-images/hkb/hkb-011.webp',
      '/project-images/hkb/hkb-012.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-013.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-014.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-015.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-016.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-017.webp',
      '/project-images/kong.webp',
      '/project-images/hkb/hkb-018.webp',
      '/project-images/hkb/hkb-019.webp',
      '/project-images/hkb/hkb-020.webp',
    ],
  },
};
