import type { ProjectDefinition } from '../../types';

export const huikuanbaoProject: ProjectDefinition = {
  id: 'huikuanbao',
  title: '回款宝重构',
  summary: '这里先接 Keynote 导出的长图，后续可替换成项目真实详情内容。',
  detail: {
    type: 'image',
    images: [
      '/project-images/hkb/hkb-001.png',
      '/project-images/hkb/hkb-002.png',
      '/project-images/hkb/hkb-003.png',
      '/project-images/hkb/hkb-004.png',
      '/project-images/hkb/hkb-005.png',
      '/project-images/hkb/hkb-006.png',
      '/project-images/hkb/hkb-007.png',
      '/project-images/hkb/hkb-008.png',
      '/project-images/hkb/hkb-009.png',
      '/project-images/hkb/hkb-010.png',
      '/project-images/hkb/hkb-011.png',
      '/project-images/hkb/hkb-012.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-013.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-014.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-015.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-016.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-017.png',
      '/project-images/kong.png',
      '/project-images/hkb/hkb-018.png',
      '/project-images/hkb/hkb-019.png',
      '/project-images/hkb/hkb-020.png',
    ],
  },
};
