import type { ProjectDefinition } from '../../types';

export const nongcunProject: ProjectDefinition = {
  id: 'nongcun',
  title: '农村金融调研',
  detail: {
    type: 'image',
    images: [
      '/project-images/ncjr/ncjr-001.webp',
      '/project-images/ncjr/ncjr-002.webp',
      '/project-images/ncjr/ncjr-003.webp',
      '/project-images/ncjr/ncjr-004.webp',
      '/project-images/ncjr/ncjr-005.webp',
      '/project-images/kong.webp',
      '/project-images/ncjr/ncjr-006.webp',
      '/project-images/ncjr/ncjr-007.webp',
      '/project-images/ncjr/ncjr-008.webp',
      '/project-images/ncjr/ncjr-009.webp',
      '/project-images/ncjr/ncjr-010.webp',
      '/project-images/ncjr/ncjr-011.webp',
      '/project-images/ncjr/ncjr-012.webp',
      '/project-images/ncjr/ncjr-013.webp',
      '/project-images/ncjr/ncjr-014.webp',
      '/project-images/kong.webp',
      '/project-images/ncjr/ncjr-015.webp',
      '/project-images/kong.webp',
      '/project-images/ncjr/ncjr-016.webp',
      '/project-images/kong.webp',
      '/project-images/ncjr/ncjr-017.webp',
      '/project-images/ncjr/ncjr-018.webp',
      '/project-images/ncjr/ncjr-019.webp',
      '/project-images/ncjr/ncjr-020.webp',
      '/project-images/ncjr/ncjr-021.webp',
      '/project-images/ncjr/ncjr-022.webp',
      '/project-images/ncjr/ncjr-023.webp',
      '/project-images/kong.webp',
      '/project-images/ncjr/ncjr-024.webp',
      '/project-images/ncjr/ncjr-025.webp',
      '/project-images/ncjr/ncjr-027.webp',
    ],
  },
};
