import type { ProjectDefinition } from '../../types';

export const nongcunProject: ProjectDefinition = {
  id: 'nongcun',
  title: '农村金融调研',
  detail: {
    type: 'image',
    images: [
      '/project-images/ncjr/ncjr-001.png',
      '/project-images/ncjr/ncjr-002.png',
      '/project-images/ncjr/ncjr-003.png',
      '/project-images/ncjr/ncjr-004.png',
      '/project-images/ncjr/ncjr-005.png',
      '/project-images/kong.png',
      '/project-images/ncjr/ncjr-006.png',
      '/project-images/ncjr/ncjr-007.png',
      '/project-images/ncjr/ncjr-008.png',
      '/project-images/ncjr/ncjr-009.png',
      '/project-images/ncjr/ncjr-010.png',
      '/project-images/ncjr/ncjr-011.png',
      '/project-images/ncjr/ncjr-012.png',
      '/project-images/ncjr/ncjr-013.png',
      '/project-images/ncjr/ncjr-014.png',
      '/project-images/kong.png',
      '/project-images/ncjr/ncjr-015.png',
      '/project-images/kong.png',
      '/project-images/ncjr/ncjr-016.png',
      '/project-images/kong.png',
      '/project-images/ncjr/ncjr-017.png',
      '/project-images/ncjr/ncjr-018.png',
      '/project-images/ncjr/ncjr-019.png',
      '/project-images/ncjr/ncjr-020.png',
      '/project-images/ncjr/ncjr-021.png',
      '/project-images/ncjr/ncjr-022.png',
      '/project-images/ncjr/ncjr-023.png',
      '/project-images/kong.png',
      '/project-images/ncjr/ncjr-024.png',
      '/project-images/ncjr/ncjr-025.png',
      '/project-images/ncjr/ncjr-027.png',
    ],
  },
};
