import type { ProjectDefinition } from '../../types';

export const thzrProject: ProjectDefinition = {
  id: 'thzr',
  title: '他行转入优化',
  detail: {
    type: 'image',
    images: [
      '/project-images/thzr/thzr-001.webp',
      '/project-images/thzr/thzr-002.webp',
      '/project-images/thzr/thzr-003.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-004.webp',
      '/project-images/thzr/thzr-005.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-006.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-007.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-008.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-009.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-010.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-011.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-012.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-013.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-014.webp',
      '/project-images/kong.webp',
      '/project-images/thzr/thzr-015.webp',
    ],
  },
};
